### ISSUE TITLE
USER STORY: Respond to poll

### ISSUE THREAD

**Issue by TeodoraAlina** [TeodoraAlina/My-First-Agile-Project#3]
In order to **give my opinion on a subject** as a **user**, I can **choose and select an answer from the poll**

# Acceptance Criteria:
* The options should be provided with radio buttons.
* The poll should have a submit button.

# Tasks:
- [ ] Create the design of the poll using HTML and CSS
- [ ] Create radio buttons for the poll
- [ ] Add a submit button and style it
